plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'com.diwan.downloader'
version = '1.0.0'

android {
  namespace 'com.diwan.downloader'
  defaultConfig {
    testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
  }
}

dependencies {
  implementation 'io.github.junkfood02.youtubedl-android:library:0.18.1'
  implementation 'io.github.junkfood02.youtubedl-android:ffmpeg:0.18.1'
  androidTestImplementation 'androidx.test.ext:junit:1.3.0'
  androidTestImplementation 'androidx.test:runner:1.7.0'
}